[package]
name = "ferrous-socks"
version = "1.0.0"
authors = ["James Brown <jbrown@easypost.com>"]
edition = "2018"
license = "ISC"
readme = "README.md"
repository = "https://github.com/EasyPost/ferrous-socks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
derive_more = "0.99"
byteorder = "1"
log = "0.4"
env_logger = "0.7"
clap = "2"
toml = "0.5"
serde = "1"
serde_derive = "1"
ip_network = { version = "0.3", features = ["serde"] }
socket2 = "0.3"
serde_json = "1"
net2 = "0.2"
syslog = "5"

[badges]
travis-ci = { repository = "EasyPost/ferrous-socks", branch = "master" }
