# this is the address to listen on for incoming sesions
listen-address = "[::1]:8080"
# this is a list of addresses to bind to for outgoing connections. If not passed, it defaults to [0.0.0.0, ::].
# if you don't pass any IPv4 addresses, IPv4 requests will be deined. Ditto for IPv6.
# 0.0.0.0 and :: are treated as INADDR_ANY (even on platforms where that's not what INADDR_ANY is defined as) and use
# your platform's default binding semantics. This does not handle subnet-routing detection; if you pass multiple bind
# addresses for a single protocol, they are simply used in order. You should only pass addresses that are globally routed.
bind-addresses = [
    "0.0.0.0",
    "::",
]
# this timeout is only applied to the connect phase
connect-timeout-ms = 3000
# this timeout is applied to the entire request
total-timeout-ms = 1800000
# this address is listened to for stats requests. if it starts with /, it is a stream-mode UNIX domain socket;
# otherwise, it is a TCP socket address
stats-socket-listen-address = "[::1]:8081"
# this ACL is evaluated sequentially; the first rule that maches has its action applied
acl = [
    {destination_network = "192.168.0.0/16", action="Reject"},
    {destination_network = "172.16.0.0/12", action="Reject"},
    {destination_network = "10.0.0.0/8", action="Reject"},
    {destination_network = "fc00::/7", action="Reject"},
    {destination_network = "fe80::/10", action="Reject"},
    {destination_network = "127.0.0.0/8", action="Reject"},
    {destination_network = "::1/128", action="Reject"},
    {destination_port = 443, action = "Allow"},
    {destination_port = 80, action = "Allow"},
    {destination_port = 22, action = "Allow"},
    {username = "imap-user", destination_port = 993, action = "Allow"},
    {username = "backdoor", action = "Allow"},
]
# if no rules in the ACL match, this rule is applied
acl-default-action = "Reject"
# whether or not to expect the PROXY protocol
expect-proxy = false
# whether or not to set SO_REUSEPORT on supported platforms
reuse-port = false
