name: CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
        default: true
    - name: cargo fmt -- --check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
        default: true
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
        default: true
    - name: Install cargo-audit binary crate
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-audit
        version: latest
        use-tool-cache: true
    - name: cargo audit
      uses: actions-rs/cargo@v1
      with:
        command: audit
        args: --ignore RUSTSEC-2020-0071
